<a href="https://colab.research.google.com/github/tgresearch/PlatzyCourses/blob/main/clase5_8platzyDLpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive


##CLASE # 5

In [ ]:
%cd '/gdrive/My Drive'

/gdrive/My Drive


In [ ]:
!git clone https://github.com/JuanPabloMF/dl-pytorch

Cloning into 'dl-pytorch'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 36 (delta 18), reused 27 (delta 9), pack-reused 0
Unpacking objects: 100% (36/36), done.


In [ ]:
%cd dl-pytorch!     

[Errno 2] No such file or directory: 'dl-pytorch!ls'
/gdrive/My Drive/dl-pytorch


In [ ]:
!ls

datasets  optimizers_viz.py  plot_helpers.py  utils.py


In [ ]:
%cd datasets

/gdrive/My Drive/dl-pytorch/datasets


In [ ]:
!ls

64x64_SIGNS.zip


In [ ]:
!unzip 64x64_SIGNS.zip

Archive:  64x64_SIGNS.zip
   creating: 64x64_SIGNS/
  inflating: 64x64_SIGNS/.DS_Store   
   creating: 64x64_SIGNS/train_signs/
  inflating: 64x64_SIGNS/train_signs/5_IMG_5556.jpg  
  inflating: 64x64_SIGNS/train_signs/3_IMG_6138.jpg  
  inflating: 64x64_SIGNS/train_signs/3_IMG_6104.jpg  
  inflating: 64x64_SIGNS/train_signs/5_IMG_5595.jpg  
  inflating: 64x64_SIGNS/train_signs/5_IMG_5581.jpg  
  inflating: 64x64_SIGNS/train_signs/1_IMG_4495.jpg  
  inflating: 64x64_SIGNS/train_signs/4_IMG_5357.jpg  
  inflating: 64x64_SIGNS/train_signs/2_IMG_4648.jpg  
  inflating: 64x64_SIGNS/train_signs/4_IMG_5343.jpg  
  inflating: 64x64_SIGNS/train_signs/2_IMG_4660.jpg  
  inflating: 64x64_SIGNS/train_signs/4_IMG_5419.jpg  
  inflating: 64x64_SIGNS/train_signs/1_IMG_4456.jpg  
  inflating: 64x64_SIGNS/train_signs/4_IMG_5394.jpg  
  inflating: 64x64_SIGNS/train_signs/1_IMG_4442.jpg  
  inflating: 64x64_SIGNS/train_signs/5_IMG_5620.jpg  
  inflating: 64x64_SIGNS/train_signs/2_IMG_4728.jpg  
  inflat

In [ ]:
import sys
course_path = '/gdrive/My Drive/dl-pytorch'
sys.path.append(course_path)

In [ ]:
import plot_helpers

In [ ]:
dir(plot_helpers)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'french',
 'imshow',
 'io',
 'np',
 'plot_cube',
 'plot_rgb_image',
 'plt',
 'torch',
 'visualize_model']

pasar a codigo en pytorch

##CLASE # 6

In [ ]:
import torch

In [ ]:
A =torch.randn((8,3,5))

In [ ]:
A.size()

torch.Size([8, 3, 5])

In [ ]:
A.size() == (8,3,5)

True

In [ ]:
#A[0][0][0]
#A[0,0,0]
A[0,:,0]

tensor([-2.2072, -0.1922,  0.2146])

In [ ]:
C = torch.zeros((5,5))

In [ ]:
C.dtype

torch.float32

In [ ]:
D = torch.randint(2,(5,5))

In [ ]:
D

tensor([[1, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [1, 1, 0, 0, 0],
        [1, 1, 0, 0, 1],
        [0, 1, 0, 0, 1]])

In [ ]:
D.dtype

torch.int64

In [ ]:
C + D
#c +D.float()

tensor([[1., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 1.],
        [0., 1., 0., 0., 1.]])

In [ ]:
torch.set_default_tensor_type('torch.FloatTensor')

In [ ]:
C.device
D.device

device(type='cpu')

In [ ]:
torch.cuda.is_available()

False

##CLASE #7

In [ ]:
# ir a entorno de ejecucion y activar GPU
import torch
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [ ]:
x=torch.randn(3,5)#cpu
y=torch.ones_like(x, device=device)#gpu

In [ ]:
x = x.to(device)

In [ ]:
z = x + y 

In [ ]:
print(z)
print(z.cpu())

tensor([[2.5743, 3.6365, 2.7374, 2.4702, 2.5950],
        [1.9663, 3.0476, 1.6825, 3.6779, 1.2996],
        [2.9634, 2.6593, 2.1972, 2.2801, 1.7070]], device='cuda:0')
tensor([[2.5743, 3.6365, 2.7374, 2.4702, 2.5950],
        [1.9663, 3.0476, 1.6825, 3.6779, 1.2996],
        [2.9634, 2.6593, 2.1972, 2.2801, 1.7070]])


In [ ]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive


In [ ]:
from torchvision import datasets

In [ ]:
dir(datasets)

['CIFAR10',
 'CIFAR100',
 'Caltech101',
 'Caltech256',
 'CelebA',
 'Cityscapes',
 'CocoCaptions',
 'CocoDetection',
 'DatasetFolder',
 'EMNIST',
 'FakeData',
 'FashionMNIST',
 'Flickr30k',
 'Flickr8k',
 'HMDB51',
 'ImageFolder',
 'ImageNet',
 'KMNIST',
 'Kinetics400',
 'Kitti',
 'LSUN',
 'LSUNClass',
 'MNIST',
 'Omniglot',
 'PhotoTour',
 'Places365',
 'QMNIST',
 'SBDataset',
 'SBU',
 'SEMEION',
 'STL10',
 'SVHN',
 'UCF101',
 'USPS',
 'VOCDetection',
 'VOCSegmentation',
 'VisionDataset',
 'WIDERFace',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_utils',
 'caltech',
 'celeba',
 'cifar',
 'cityscapes',
 'coco',
 'fakedata',
 'flickr',
 'folder',
 'hmdb51',
 'imagenet',
 'kinetics',
 'kitti',
 'lsun',
 'mnist',
 'omniglot',
 'phototour',
 'places365',
 'sbd',
 'sbu',
 'semeion',
 'stl10',
 'svhn',
 'ucf101',
 'usps',
 'utils',
 'video_utils',
 'vision',
 'voc',
 'widerface']

In [ ]:
cifar = datasets.CIFAR10('/gdrive/My Drive/dl-pytorch/datasets', download=True)

  0%|          | 0/170498071 [00:00<?, ?it/s]

Extracting /gdrive/My Drive/dl-pytorch/datasets/cifar-10-python.tar.gz to /gdrive/My Drive/dl-pytorch/datasets


In [ ]:
len(cifar)

50000

In [ ]:
cifar.data

array([[[[ 59,  62,  63],
         [ 43,  46,  45],
         [ 50,  48,  43],
         ...,
         [158, 132, 108],
         [152, 125, 102],
         [148, 124, 103]],

        [[ 16,  20,  20],
         [  0,   0,   0],
         [ 18,   8,   0],
         ...,
         [123,  88,  55],
         [119,  83,  50],
         [122,  87,  57]],

        [[ 25,  24,  21],
         [ 16,   7,   0],
         [ 49,  27,   8],
         ...,
         [118,  84,  50],
         [120,  84,  50],
         [109,  73,  42]],

        ...,

        [[208, 170,  96],
         [201, 153,  34],
         [198, 161,  26],
         ...,
         [160, 133,  70],
         [ 56,  31,   7],
         [ 53,  34,  20]],

        [[180, 139,  96],
         [173, 123,  42],
         [186, 144,  30],
         ...,
         [184, 148,  94],
         [ 97,  62,  34],
         [ 83,  53,  34]],

        [[177, 144, 116],
         [168, 129,  94],
         [179, 142,  87],
         ...,
         [216, 184, 140],
        

In [ ]:
data = torch.Tensor(cifar.data)

In [ ]:
data.size()

torch.Size([50000, 32, 32, 3])

-> del data size vemos que el tensor es de 4 dimensiones; 
1era -> apilar todas la imagenes del dataset
2-> pixeles 32 x 32 (imagenes que tratamos)
3-> cantidad de canales (3matrizes RGB -cubo)

# CLASE #8

In [ ]:
import torch
import torch.nn as nn
#instanciar 3 capaz
linear = nn.Linear(in_features=4096, out_features=10) # toma solo tensores de dimesion 1 input
#crear capa convolucional
conv = nn.Conv2d(in_channels=3,out_channels=9, kernel_size=3,stride=1, padding=1) #modificar canales pero no modifica el tamano de la imagen
#efecto sobre la dimension del tensor debe ser clara
relu = nn.ReLU(False)


In [ ]:
#las capas son una funcion, intentemos un x-> y
x = torch.randn(4096)
y = linear(x) #transformacion lineal -> multiplicacion de por una matriz
y.size()

torch.Size([10])

In [ ]:
x = torch.randn(1,3,7,7)
y = conv(x)
z = relu(x)
y.size()

torch.Size([1, 9, 7, 7])

In [ ]:
x

tensor([[[[-6.7222e-01,  8.9782e-01, -6.5079e-01, -4.0107e-01, -1.1279e+00,
            1.9186e-01,  9.5131e-01],
          [-3.0082e-01, -5.9945e-02, -1.9667e-01, -9.7337e-01, -7.7140e-01,
           -4.1813e-01,  3.6689e-01],
          [ 1.4106e+00, -2.4249e+00, -1.2859e-01, -2.0203e-01,  1.2177e-01,
            3.5669e-01, -1.7099e+00],
          [ 5.0759e-01, -1.1446e+00, -3.9091e-01,  1.3660e+00, -3.0783e-01,
            2.3051e+00,  1.4421e-02],
          [-1.9685e-01,  2.9094e-01, -4.1680e-01, -6.1323e-01,  1.2325e+00,
           -1.0920e+00, -1.5093e+00],
          [ 7.5027e-02,  8.9265e-01, -6.2308e-01, -3.5901e-01, -1.7316e+00,
            3.8904e-01, -1.3222e+00],
          [ 7.5249e-01,  6.2341e-01, -7.9815e-01,  1.0206e+00,  1.0154e+00,
           -9.6533e-01,  7.4109e-01]],

         [[ 5.5953e-02, -1.4041e+00, -8.8293e-01,  2.3953e-01, -1.3847e+00,
           -9.3247e-01,  1.7131e-01],
          [-5.4604e-01,  2.8160e-01, -5.2566e-01,  6.3195e-02, -3.1393e-01,
          

In [ ]:
z
#aplana a zero los negativos

tensor([[[[0.0000, 0.8978, 0.0000, 0.0000, 0.0000, 0.1919, 0.9513],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.3669],
          [1.4106, 0.0000, 0.0000, 0.0000, 0.1218, 0.3567, 0.0000],
          [0.5076, 0.0000, 0.0000, 1.3660, 0.0000, 2.3051, 0.0144],
          [0.0000, 0.2909, 0.0000, 0.0000, 1.2325, 0.0000, 0.0000],
          [0.0750, 0.8927, 0.0000, 0.0000, 0.0000, 0.3890, 0.0000],
          [0.7525, 0.6234, 0.0000, 1.0206, 1.0154, 0.0000, 0.7411]],

         [[0.0560, 0.0000, 0.0000, 0.2395, 0.0000, 0.0000, 0.1713],
          [0.0000, 0.2816, 0.0000, 0.0632, 0.0000, 0.6967, 0.0000],
          [0.0000, 0.6508, 1.2393, 1.4677, 0.0000, 1.7207, 0.6469],
          [0.0000, 0.0000, 0.0000, 0.4359, 0.0027, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.1967, 0.5851, 0.0799, 2.3063],
          [0.2458, 0.5225, 0.0000, 0.0000, 0.2656, 0.0000, 0.0000],
          [0.1256, 1.8969, 0.0000, 0.0000, 0.7347, 0.6964, 0.0000]],

         [[0.5393, 0.0854, 0.0000, 0.0000, 0

In [ ]:
for name, p in linear.named_parameters():
  print(name)
  print(p.size())
  print()

weight
torch.Size([10, 4096])

bias
torch.Size([10])

